version: '3.8'

services:
  backend:
    build: ./backend
    container_name: php-backend
    ports:
      - "8000:80"                      # expose Apache sur le port 8000 de la machine
    volumes:
      - ./backend:/var/www/html       # pour recharger le code sans rebuild
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"                    # expose React sur le port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true      # utile sous Docker pour que React détecte les fichiers modifiés
    volumes:
      - ./frontend:/app
      - /app/node_modules             # monte un volume vide pour node_modules
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dejavu
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"                    # accès local sur 3307 → MySQL 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
