name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🚧 Build & Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du code
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2) Backend
      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Installer les dépendances Backend
        working-directory: backend
        run: composer install --no-dev --optimize-autoloader

      - name: Archiver le Backend
        run: |
          cd backend
          zip -r ../backend-artifact.zip ./*

      - name: Publier l’artefact Backend
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: backend-artifact.zip

      # 3) Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances Frontend
        working-directory: frontend
        run: npm ci

      - name: Builder le Frontend
        working-directory: frontend
        run: npm run build

      - name: Archiver le Build Frontend
        run: |
          cd frontend
          zip -r ../frontend-artifact.zip build

      - name: Publier l’artefact Frontend
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend-artifact.zip

  deploy:
    name: 🚀 Déploiement sur Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Télécharger l’artefact Backend
        uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: .

      - name: Télécharger l’artefact Frontend
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: .

      - name: Installer rsync et SSH
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Ajouter la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ajouter Azure à known_hosts
        run: ssh-keyscan -H "${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Déployer via deploy.sh
        run: bash ./deploy.sh
        env:
          AZURE_SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
          AZURE_VM_IP:   ${{ secrets.AZURE_VM_IP }}
          MYSQL_ROOT_PWD:${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_NAME:       ${{ secrets.DB_NAME }}

