name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🚧 Build artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend build
      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Backend deps
        working-directory: backend
        run: composer install --no-dev --optimize-autoloader

      - name: Archive Backend
        run: |
          cd backend
          zip -r ../backend-artifact.zip ./*

      - name: Upload Backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: backend-artifact.zip

      # Frontend build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Archive Frontend build
        run: |
          cd frontend
          zip -r ../frontend-artifact.zip build

      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend-artifact.zip

  deploy:
    name: 🚀 Deploy to VM
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-build
          path: .

      - name: Download Frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: .

      - name: Install rsync & ssh
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Known hosts for VM
        run: ssh-keyscan -H "${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Run remote deploy script
        env:
          KEY: ~/.ssh/id_rsa
          USER: azureuser
          HOST: ${{ secrets.AZURE_VM_IP }}
        run: |
          bash deploy.sh
