name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🚧 Build & Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      # 1) Récup du code
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2) Build backend (composer install + zip)
      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Installer les dépendances Backend
        run: |
          cd backend
          composer install --no-dev --optimize-autoloader
      - name: Archiver le Backend
        run: |
          cd backend
          zip -r ../backend-artifact.zip ./*
      - name: Publier l’artefact Backend
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: backend-artifact.zip

      # 3) Build frontend (npm ci + build + zip)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Installer les dépendances Frontend
        run: |
          cd frontend
          npm ci
      - name: Builder le Frontend
        env:
          CI: false
        run: |
          cd frontend
          npm run build
      - name: Archiver le Build Frontend
        run: |
          cd frontend
          zip -r ../frontend-artifact.zip build
      - name: Publier l’artefact Frontend
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend-artifact.zip
