name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Déploiement
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql

      - name: Installer les dépendances backend
        run: |
          cd backend
          composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer & builder le frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Déployer sur le serveur
        uses: appleboy/ssh-action@v0.1.12
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Arrêt du serveur Apache (si déjà en service)
            sudo systemctl stop apache2 || true

            # Synchronisation du backend
            rsync -av --delete ./backend/ $REMOTE_APP_PATH/backend/

            # Synchronisation du build frontend
            rsync -av --delete ./frontend/build/ $REMOTE_APP_PATH/frontend/

            # Ajustement des permissions
            sudo chown -R www-data:www-data $REMOTE_APP_PATH

            # Relance d’Apache
            sudo systemctl start apache2
