name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    name: Tests PHP (Backend)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: projet
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP & extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, mysqli

      - name: Install Composer dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL…"
            sleep 2
          done

      - name: Run PHPUnit
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: projet
          DB_USERNAME: user
          DB_PASSWORD: password
        run: vendor/bin/phpunit --colors=always --coverage-text

  frontend:
    name: Tests JS (Frontend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JS dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Jest
        working-directory: frontend
        run: npm test -- --ci --passWithNoTests
