name: Déploiement DejaVu sur Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer les dépendances SSH et rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      - name: Ajouter la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ajouter l’hôte Azure à known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.AZURE_VM_IP }}" >> ~/.ssh/known_hosts

      - name: Lancer le script de déploiement
        env:
          MYSQL_ROOT_PWD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          bash deploy.sh